// @autogenerated

// WARNING THIS FILE IS AUTOGENERATED! DO NOT EDIT!

import React from 'react';

import H1 from '@govtnz/ds/build/react-ts/H1';
import '../../commons/styles/ds/themed-H1.scss';

import H2 from '@govtnz/ds/build/react-ts/H2';
import '../../commons/styles/ds/themed-H2.scss';

import PatternsPage from '../../components/PatternsPage';
import onChangeGenerator from '../../commons/onChangeGenerator';

const PageContent = props => (
  <React.Fragment>
    <H1 styleSize="xlarge" id="main-heading">
      Prototypes
    </H1>
    <p>
      Intorduction paragraph tp tell users that they can fiond prototypes of DS
      here. More cotent content goes here.
    </p>
    <H2 styleSize="large" id="main-heading">
      Contact us form prototype
    </H2>
    <p>
      Intro copy i.e here you can see how we use DS for elements to assemble
      example of a comtact us for <a href="/">Link to source code</a>.
    </p>
    <p>This is purely for demonstration purpose. Not an advice</p>
  </React.Fragment>
);

const template = props => {
  return (
    <PatternsPage
      title="Patterns"
      pageProps={props}
      PageContent={PageContent}
    />
  );
};

export default template;
