// @autogenerated

// WARNING THIS FILE IS AUTOGENERATED! DO NOT EDIT!

import React, { Fragment } from 'react';
import ReactDOM from 'react-dom';

import FlexContainer from '@govtnz/ds/build/react-ts/FlexContainer.tsx';import FlexRow from '@govtnz/ds/build/react-ts/FlexRow.tsx';import FlexColumn from '@govtnz/ds/build/react-ts/FlexColumn.tsx';
const onChangeGenerator = comp => ({});
const ExampleContainer = ({ children }) => <Fragment>{children}</Fragment>;
const ExampleHeading = ({ children }) => <Fragment>{children}</Fragment>;
const ExampleSection = ({ children }) => <Fragment>{children}</Fragment>;
const Example = ({ children }) => <Fragment>{children}</Fragment>;

var PageContent = (props) => (<Example {...onChangeGenerator(Example)}>
        <FlexContainer {...onChangeGenerator(FlexContainer)} width="fixed">
            <FlexRow {...onChangeGenerator(FlexRow)}>
                <FlexColumn {...onChangeGenerator(FlexColumn)} xs="4" sm="4" md="4" lg="4"> .g-flex-col .g-flex-col-md-4 </FlexColumn>
                <FlexColumn {...onChangeGenerator(FlexColumn)} xs="4" sm="4" md="4" lg="4"> .g-flex-col .g-flex-col-md-4 </FlexColumn>
                <FlexColumn {...onChangeGenerator(FlexColumn)} xs="4" sm="4" md="4" lg="4"> .g-flex-col .g-flex-col-md-4 </FlexColumn>
            </FlexRow>
        </FlexContainer>
    </Example>);

    document.addEventListener('DOMContentLoaded', () => {
      const selector = '#root';
      const root = document.querySelector(selector);
      if (!root) {
        console.error("Couldn't find app mount point ", selector);
        return;
      }
      ReactDOM.hydrate(<PageContent />, root, window.afterRender);
    });
    