// @autogenerated

// WARNING THIS FILE IS AUTOGENERATED! DO NOT EDIT!

import React, { Fragment } from 'react';
import ReactDOM from 'react-dom';

import FieldsetBlock from '@govtnz/ds/build/react-ts/FieldsetBlock.tsx';import H1 from '@govtnz/ds/build/react-ts/H1.tsx';import RadioBlock from '@govtnz/ds/build/react-ts/RadioBlock.tsx';
const onChangeGenerator = comp => ({});
const ExampleContainer = ({ children }) => <Fragment>{children}</Fragment>;
const ExampleHeading = ({ children }) => <Fragment>{children}</Fragment>;
const ExampleSection = ({ children }) => (
  <div className="example__section">{children}</div>
);
const Example = ({ children }) => <Fragment>{children}</Fragment>;

var PageContent = (props) => (<Example {...onChangeGenerator(Example)}>
        <FieldsetBlock {...onChangeGenerator(FieldsetBlock)} legend={<H1 {...onChangeGenerator(H1)} styleSize="large" id="whereLiveTitle">Where do you live?</H1>}>
            <RadioBlock {...onChangeGenerator(RadioBlock)} label="North Island" radioId="anyRadioId3334" name="where" value="north" labelId="labelId3" />
            <RadioBlock {...onChangeGenerator(RadioBlock)} label="South Island" radioId="anyRadioId42344" name="where" value="south" labelId="labelId4" />
            <RadioBlock {...onChangeGenerator(RadioBlock)} label="Stewart Island" radioId="anyRadioId5234" name="where" value="stewart" labelId="labelId5" />
            <RadioBlock {...onChangeGenerator(RadioBlock)} label="Chatham Islands" radioId="anyRadioId6234" name="where" value="chatham" labelId="labelId6" />
        </FieldsetBlock>
    </Example>);

    document.addEventListener('DOMContentLoaded', () => {
      const selector = '#root';
      const root = document.querySelector(selector);
      if (!root) {
        console.error("Couldn't find app mount point ", selector);
        return;
      }
      ReactDOM.hydrate(<PageContent />, root, window.afterRender);
    });
    