// @autogenerated

// WARNING THIS FILE IS AUTOGENERATED! DO NOT EDIT!

import React, { Fragment } from 'react';
import ReactDOM from 'react-dom';

import Textarea from '@govtnz/ds/build/react-ts/Textarea.tsx';import TextareaWithCustomRows from '@govtnz/ds/build/react-ts/TextareaWithCustomRows.tsx';import TextareaWithErrorMessage from '@govtnz/ds/build/react-ts/TextareaWithErrorMessage.tsx';
const onChangeGenerator = comp => ({});
const ExampleContainer = ({ children }) => <Fragment>{children}</Fragment>;
const ExampleHeading = ({ children }) => <Fragment>{children}</Fragment>;
const ExampleSection = ({ children }) => (
  <div className="example__section">{children}</div>
);
const Example = ({ children }) => <Fragment>{children}</Fragment>;

var PageContent = (props) => (<Example {...onChangeGenerator(Example)}>
        <Textarea {...onChangeGenerator(Textarea)} />
        <TextareaWithCustomRows {...onChangeGenerator(TextareaWithCustomRows)} />
        <TextareaWithErrorMessage {...onChangeGenerator(TextareaWithErrorMessage)} />
    </Example>);

    document.addEventListener('DOMContentLoaded', () => {
      const selector = '#root';
      const root = document.querySelector(selector);
      if (!root) {
        console.error("Couldn't find app mount point ", selector);
        return;
      }
      ReactDOM.hydrate(<PageContent />, root, window.afterRender);
    });
    