// @autogenerated

// WARNING THIS FILE IS AUTOGENERATED! DO NOT EDIT!

import React, { Fragment } from 'react';

import P from '@govtnz/ds/build/react-ts/P.tsx';
import '@govtnz/ds/build/css/P.css';
import A from '@govtnz/ds/build/react-ts/A.tsx';
import '@govtnz/ds/build/css/A.css';

import IframePage from '../../components/IframePage';
import onChangeGenerator from '../../commons/onChangeGenerator';
const ExampleContainer = ({ children }) => <Fragment>{children}</Fragment>;
const ExampleHeading = ({ children }) => <Fragment>{children}</Fragment>;
const ExampleSection = ({ children }) => <Fragment>{children}</Fragment>;
const Example = ({ children }) => <Fragment>{children}</Fragment>;

const PageContent = (props) => (<Example {...onChangeGenerator(Example)}>
        <P styleSize="medium"><A href="http://example.com/">Normal link</A></P>
    </Example>);

const template = props => {
  return (
    <IframePage
      title={"Example of a Link"}
      id={"iframe_componentsA0"}
      parentUrl={"../A"}
      pageProps={props}
      PageContent={PageContent}
    />
  );
};

export default template;
