// @autogenerated

// WARNING THIS FILE IS AUTOGENERATED! DO NOT EDIT!

import React, { Fragment } from 'react';

import BackLinkWithCustomText from '@govtnz/ds/build/react-ts/BackLinkWithCustomText.tsx';
import '@govtnz/ds/build/css/BackLinkWithCustomText.css';

import IframePage from '../../components/IframePage';
import ExampleContainer from '../../commons/ExampleContainer';
import ExampleHeading from '../../commons/ExampleHeading';
import ExampleSection from '../../commons/ExampleSection';
import onChangeGenerator from '../../commons/onChangeGenerator';
const Example = ({ children }) => <Fragment>{children}</Fragment>;

const PageContent = (props) => (<Example {...onChangeGenerator(Example)}>
        <BackLinkWithCustomText {...onChangeGenerator(BackLinkWithCustomText)} />
    </Example>);

const template = props => {
  return (
    <IframePage
      title={"Example of Back link"}
      id={"iframe_componentsBackLink0"}
      parentUrl={"../BackLink"}
      pageProps={props}
      PageContent={PageContent}
    />
  );
};

export default template;
