// @autogenerated

// WARNING THIS FILE IS AUTOGENERATED! DO NOT EDIT!

// Developer note: these files are treated as templates and called from prebuild.js
// They shouldn't be imported and used directly.

import React from 'react';
import { Link } from 'gatsby';
import onChangeGenerator from '../../commons/onChangeGenerator';
import P from '@govtnz/ds/build/react-ts/P.tsx';
import '@govtnz/ds/build/css/P.css';
import H2 from '@govtnz/ds/build/react-ts/H2.tsx';
import '@govtnz/ds/build/css/H2.css';
import Button from '@govtnz/ds/build/react-ts/Button.tsx';
import '@govtnz/ds/build/css/Button.css';
import Ul from '@govtnz/ds/build/react-ts/Ul.tsx';
import '@govtnz/ds/build/css/Ul.css';
import Li from '@govtnz/ds/build/react-ts/Li.tsx';
import '@govtnz/ds/build/css/Li.css';
import components__Button from '../../commons/examples/components__Button';
// Indirect relative import because this template is output to src/pages/components so it needs to step back to `commons`.
import ComponentPage from '../../commons/component-page';
import ComponentCode from '../../commons/component-code';
import Example from '../../commons/Example';
import ExampleContainer from '../../commons/ExampleContainer';
import ExampleHeading from '../../commons/ExampleHeading';
import ExampleSection from '../../commons/ExampleSection';

const PageContent = (props) => <React.Fragment><P styleSize="large">
    Buttons make important actions stand out within a task flow, and help users
    to do that action easily. Colours, labels or icons are used on buttons to
    guide users about the action that will happen when they touch or
    click the button.
</P>

<H2 {...onChangeGenerator(H2)} styleSize="large" id="examples">Examples</H2>
<p>Interact with each example to see how it works.</p>
<ExampleContainer {...onChangeGenerator(ExampleContainer)}>
    <Example {...onChangeGenerator(Example)} code={components__Button[0]} >
        <Button {...onChangeGenerator(Button)} type="Button">Save and continue</Button>
    </Example>
</ExampleContainer>

<h2 id="when-to-use-it">When to use it</h2>
<p>Use buttons to help users carry out key actions in a task flow, like starting
an application or saving their information.</p>
<h2 id="how-it-works">How it works</h2>
<p>Write button labels in sentence case, describing the action it performs.
For example:</p>
<Ul {...onChangeGenerator(Ul)} bulleted>
<Li {...onChangeGenerator(Li)}>&#39;Start now&#39; at the start of the service</Li>
<Li {...onChangeGenerator(Li)}>&#39;Sign in&#39; to an account a user has already created</Li>
<Li {...onChangeGenerator(Li)}>&#39;Continue&#39; when the service does not save a user&#39;s information</Li>
<Li {...onChangeGenerator(Li)}>&#39;Save and continue&#39; when the service does save a user&#39;s information</Li>
<Li {...onChangeGenerator(Li)}>&#39;Save and come back later&#39; when a user can save their information and
come back later</Li>
<Li {...onChangeGenerator(Li)}>&#39;Add another&#39; to add another item to a list or group</Li>
<Li {...onChangeGenerator(Li)}>&#39;Pay&#39; to make a payment</Li>
<Li {...onChangeGenerator(Li)}>&#39;Confirm and send&#39; on a check answers page that does not have any legal
content a user must agree to</Li>
<Li {...onChangeGenerator(Li)}>&#39;Accept and send&#39; on a check answers page that has legal content a user
must agree to</Li>
<Li {...onChangeGenerator(Li)}>&#39;Sign out&#39; when a user is leaving an account that they signed in to.</Li>
</Ul>
<p>You may need to include more or different words to clearly describe a button&#39;s
action. For example, &#39;Add another address&#39; or &#39;Accept and claim a tax refund&#39;.</p>
<p>Align the primary action button to the left edge of your form.</p>
<ExampleContainer {...onChangeGenerator(ExampleContainer)}>
    <ExampleHeading {...onChangeGenerator(ExampleHeading)}>Default buttons</ExampleHeading>
    <Example {...onChangeGenerator(Example)} code={components__Button[1]} >
        <Button {...onChangeGenerator(Button)} type="Button">Save and continue</Button>
    </Example>
</ExampleContainer>

<p>Use a default button for the main &#39;call to action&#39; on a page.</p>
<p>Avoid using multiple default buttons on a single page. Having more than one
main call to action reduces their impact, and makes it harder for users to
know what to do next.</p>
<ExampleContainer {...onChangeGenerator(ExampleContainer)}>
    <ExampleHeading {...onChangeGenerator(ExampleHeading)}>Secondary buttons</ExampleHeading>
    <Example {...onChangeGenerator(Example)} code={components__Button[2]} >
        <Button {...onChangeGenerator(Button)} type="Button" kind="secondary">Find address</Button>
    </Example>
</ExampleContainer>

<p>Use secondary buttons for secondary calls to action on a page.</p>
<p>Pages with too many calls to action make it hard for users to know what to do
next. Before adding lots of secondary buttons, try to simplify the page or
break the content down into several pages.</p>
<ExampleContainer {...onChangeGenerator(ExampleContainer)}>
    <ExampleHeading {...onChangeGenerator(ExampleHeading)}>Primary and secondary combination</ExampleHeading>
    <Example {...onChangeGenerator(Example)} code={components__Button[3]} >
        <Button {...onChangeGenerator(Button)} type="Button">Save and continue</Button>
        <Button {...onChangeGenerator(Button)} type="Button" kind="secondary">Save as draft</Button>
    </Example>
</ExampleContainer>

<p>You can use secondary buttons in combination with default buttons. Limit
combinations to two buttons only, as more can confuse users.</p>
<ExampleContainer {...onChangeGenerator(ExampleContainer)}>
    <ExampleHeading {...onChangeGenerator(ExampleHeading)}>Warning buttons</ExampleHeading>
    <Example {...onChangeGenerator(Example)} code={components__Button[4]} >
        <Button {...onChangeGenerator(Button)} type="Button" kind="warning">Delete account</Button>
    </Example>
</ExampleContainer>

<p>Warning buttons are designed to make users think carefully before they use
them. They only work if used very sparingly. Most services should
not need one.</p>
<p>Only use warning buttons for actions with serious destructive consequences
that cannot be easily undone by a user. For example, permanently
deleting an account.</p>
<p>When letting users carry out an action like this, it&#39;s a good idea to include
an additional step beforehand that asks users to confirm they want to do
the destructive action.</p>
<p>In this instance, use another style of button for the initial call to action,
and a warning button for the final confirmation.</p>
<p>Do not only rely solely on the red colour of a warning button to communicate
the serious nature of the action. This is because not all users will be able to
see the colour or may not understand what it signifies. Make sure the context
and button text make clear what will happen if the user selects it.</p>
<ExampleContainer {...onChangeGenerator(ExampleContainer)}>
    <ExampleHeading {...onChangeGenerator(ExampleHeading)}>Disabled buttons</ExampleHeading>
    <Example {...onChangeGenerator(Example)} code={components__Button[5]} >
        <Button {...onChangeGenerator(Button)} type="Button" disabled>Save and continue</Button>
    </Example>
</ExampleContainer>

<p>Disabled buttons have poor contrast and can confuse some users, so avoid
them if possible.</p>
<p>Only use disabled buttons if research shows it makes the user interface
easier to understand.</p>
<h2 id="credit">Credit</h2>
<p>Guidance, original HTML and CSS derived from <a href="https://github.com/alphagov/govuk-frontend">GOV.UK Design System</a>.</p>
</React.Fragment>

export default function Code(props) {
  return (
    <ComponentPage
      title={"Button"}
      id={"Button"}
      pageProps={props}
      PageContent={PageContent}
    />
  );
}
