// @autogenerated

// WARNING THIS FILE IS AUTOGENERATED! DO NOT EDIT!

import React, { Fragment } from 'react';

import Button from '@govtnz/ds/build/react-ts/Button.tsx';
import '@govtnz/ds/build/css/Button.css';

import IframePage from '../../components/IframePage';
import ExampleContainer from '../../commons/ExampleContainer';
import ExampleHeading from '../../commons/ExampleHeading';
import ExampleSection from '../../commons/ExampleSection';
import onChangeGenerator from '../../commons/onChangeGenerator';
const Example = ({ children }) => <Fragment>{children}</Fragment>;

const PageContent = (props) => (<Example {...onChangeGenerator(Example)}>
        <Button {...onChangeGenerator(Button)} type="Button" level="secondary">Find address</Button>
    </Example>);

const template = props => {
  return (
    <IframePage
      title={"Secondary buttons"}
      id={"iframe_componentsButton1"}
      parentUrl={"../Button"}
      pageProps={props}
      PageContent={PageContent}
    />
  );
};

export default template;
