// @autogenerated

// WARNING THIS FILE IS AUTOGENERATED! DO NOT EDIT!

// Developer note: these files are treated as templates and called from prebuild.js
// They shouldn't be imported and used directly.

import React from 'react';
import { Link } from 'gatsby';
import onChangeGenerator from '../../commons/onChangeGenerator';
import H2 from '@govtnz/ds/build/react-ts/H2.tsx';
import '@govtnz/ds/build/css/H2.css';
import FieldsetBlock from '@govtnz/ds/build/react-ts/FieldsetBlock.tsx';
import '@govtnz/ds/build/css/FieldsetBlock.css';
import H1 from '@govtnz/ds/build/react-ts/H1.tsx';
import '@govtnz/ds/build/css/H1.css';
import CheckboxBlock from '@govtnz/ds/build/react-ts/CheckboxBlock.tsx';
import '@govtnz/ds/build/css/CheckboxBlock.css';
import FieldsetBlockWithError from '@govtnz/ds/build/react-ts/FieldsetBlockWithError.tsx';
import '@govtnz/ds/build/css/FieldsetBlockWithError.css';
import Ul from '@govtnz/ds/build/react-ts/Ul.tsx';
import '@govtnz/ds/build/css/Ul.css';
import Li from '@govtnz/ds/build/react-ts/Li.tsx';
import '@govtnz/ds/build/css/Li.css';
import components__Checkboxes from '../../commons/examples/components__Checkboxes';
// Indirect relative import because this template is output to src/pages/components so it needs to step back to `commons`.
import ComponentPage from '../../commons/component-page';
import ComponentCode from '../../commons/component-code';
import Example from '../../commons/Example';
import ExampleContainer from '../../commons/ExampleContainer';
import ExampleHeading from '../../commons/ExampleHeading';
import ExampleSection from '../../commons/ExampleSection';

const PageContent = (props) => <React.Fragment><p>Checkboxes enable users to select one or more options from a visible list of options, and to toggle a single option on or off.</p>
<H2 {...onChangeGenerator(H2)} styleSize="large" id="examples">Examples</H2>
<p>Interact with each example to see how it works.</p>
<ExampleContainer {...onChangeGenerator(ExampleContainer)}>
    <Example {...onChangeGenerator(Example)} code={components__Checkboxes[0]} >
        <FieldsetBlock {...onChangeGenerator(FieldsetBlock)} legend={<H1 {...onChangeGenerator(H1)} styleSize="large" id="providerChoiceTitle1" marginBottom8>Who are your providers?</H1>} hint={<p>Select all that apply.</p>} hintId="hintId1">
            <CheckboxBlock {...onChangeGenerator(CheckboxBlock)} label="Aardvark Access" checkboxId="anyCheckboxId1" value="provider1" name="providerChoice1" labelId="labelId1" />
            <CheckboxBlock {...onChangeGenerator(CheckboxBlock)} label="Bumblebee Business"  checkboxId="anyCheckboxId2" value="provider2" name="providerChoice1" labelId="labelId2" />
    <CheckboxBlock {...onChangeGenerator(CheckboxBlock)} label="Caterpillar Company"  checkboxId="anyCheckboxId3" value="provider3" name="providerChoice1" labelId="labelId3" />
        </FieldsetBlock>
    </Example>
</ExampleContainer>

<ExampleContainer {...onChangeGenerator(ExampleContainer)}>
    <ExampleHeading {...onChangeGenerator(ExampleHeading)}>Error</ExampleHeading>
    <Example {...onChangeGenerator(Example)} code={components__Checkboxes[1]} >
        <FieldsetBlockWithError {...onChangeGenerator(FieldsetBlockWithError)} legend={<H1 {...onChangeGenerator(H1)} styleSize="large" id="providerChoiceTitle2" marginBottom8>Who are your providers?</H1>} hint={<p>Select all that apply.</p>} hintId="hintId21" errorId="errorId21" error="You must choose at least one provider.">
            <CheckboxBlock {...onChangeGenerator(CheckboxBlock)} label="Aardvark Access"  checkboxId="anyCheckboxId21" value="provider1" name="providerChoice2" labelId="labelId21" />
            <CheckboxBlock {...onChangeGenerator(CheckboxBlock)} label="Bumblebee Business"  checkboxId="anyCheckboxId22" value="provider2"  name="providerChoice2" labelId="labelId22" />
    <CheckboxBlock {...onChangeGenerator(CheckboxBlock)} label="Caterpillar Company"  checkboxId="anyCheckboxId23" value="provider3" name="providerChoice2" labelId="labelId23" />
        </FieldsetBlockWithError>
    </Example>
</ExampleContainer>

<ExampleContainer {...onChangeGenerator(ExampleContainer)}>
    <ExampleHeading {...onChangeGenerator(ExampleHeading)}>Checkboxes with hints</ExampleHeading>
    <Example {...onChangeGenerator(Example)} code={components__Checkboxes[2]} >
        <FieldsetBlock {...onChangeGenerator(FieldsetBlock)} legend={<H1 {...onChangeGenerator(H1)} styleSize="large" id="providerChoiceTitle3" marginBottom8>Who are your providers?</H1>} hint={<p>Select all that apply.</p>} hintId="hintId3">
            <CheckboxBlock {...onChangeGenerator(CheckboxBlock)} label="Aardvark Access" checkboxId="anyCheckboxId31" value="provider1" name="providerChoice3" labelId="labelId31" hintId="hintId31" hint="Aardvark Access provides internet" />
            <CheckboxBlock {...onChangeGenerator(CheckboxBlock)} label="Bumblebee Business"  checkboxId="anyCheckboxId32" value="provider2" name="providerChoice3" labelId="labelId32" hintId="hintId32" hint="Bumblebee Business provides electricity" />
            <CheckboxBlock {...onChangeGenerator(CheckboxBlock)} label="Caterpillar Company"  checkboxId="anyCheckboxId33" value="provider3" name="providerChoice3" labelId="labelId33" hintId="hintId33" hint="Caterpillar Company provides telephone" />
        </FieldsetBlock>
    </Example>
</ExampleContainer>

<h2 id="when-to-use-it">When to use it</h2>
<p>Use the checkboxes component when you need to help users:</p>
<Ul {...onChangeGenerator(Ul)} bulleted>
<Li {...onChangeGenerator(Li)}>select one or more options from a list</Li>
<Li {...onChangeGenerator(Li)}>toggle a single option on or off.</Li>
</Ul>
<h2 id="when-not-to-use-it">When not to use it</h2>
<p>Do not use the checkboxes component if users can only choose one option from a selection. In this case, use <Link to="/components/Radios/">radio buttons</Link> instead.</p>
<h2 id="how-it-works">How it works</h2>
<p>Checkboxes are grouped together in a <code>&lt;fieldset&gt;</code> with a <code>&lt;legend&gt;</code> that describes them, as shown in the examples on this page. This is usually a question, like ‘Who are your providers?’.</p>
<p>If you are asking just one question per page, you can set the contents of the <code>&lt;legend&gt;</code> as the page heading. This is good practice because users of screen readers will only hear the contents once.</p>
<p>Always position each checkbox to the left of its label. This makes it easier to find, especially for users of screen magnifiers.</p>
<p>Unlike with radio buttons, users can select multiple checkboxes from a list. Do not assume that users will know how many checkboxes they can select based on only the visual difference between radio buttons and checkboxes.</p>
<p>If needed, add a hint to explain this, like ‘Select all that apply’.</p>
<p>Do not pre-select checkboxes as users are likely to:</p>
<Ul {...onChangeGenerator(Ul)} bulleted>
<Li {...onChangeGenerator(Li)}>not realise they’ve missed a question</Li>
<Li {...onChangeGenerator(Li)}>submit the wrong answer.</Li>
</Ul>
<p>Order checkbox labels alphabetically by default.</p>
<p>In some cases, pre-selected ordering can be helpful, such as listing options from the most to the least common. An example is ordering answers to the question ‘What is your nationality?’ based on population size.</p>
<p>Another example of pre-selected ordering is listing options chronologically. For example, you could order possible time periods for contact from earliest to latest, so users can select the periods that suit them best.</p>
<p>However, using pre-selected ordering could reinforce bias in your service, so use it with caution. If in doubt, order alphabetically.</p>
<h2 id="credit">Credit</h2>
<p>Guidance, original HTML and CSS derived from <a href="https://github.com/alphagov/govuk-frontend">GOV.UK Design System</a>.</p>
</React.Fragment>

export default function Code(props) {
  return (
    <ComponentPage
      title={"Checkboxes"}
      id={"Checkboxes"}
      pageProps={props}
      PageContent={PageContent}
    />
  );
}
