// @autogenerated

// WARNING THIS FILE IS AUTOGENERATED! DO NOT EDIT!

// Developer note: these files are treated as templates and called from prebuild.js
// They shouldn't be imported and used directly.

import React from 'react';
import { Link } from 'gatsby';
import onChangeGenerator from '../../commons/onChangeGenerator';
import FileUpload from '@govtnz/ds/build/react-ts/FileUpload.tsx';
import '@govtnz/ds/build/css/FileUpload.css';
import FileUploadWithErrorMessage from '@govtnz/ds/build/react-ts/FileUploadWithErrorMessage.tsx';
import '@govtnz/ds/build/css/FileUploadWithErrorMessage.css';
import H2 from '@govtnz/ds/build/react-ts/H2.tsx';
import '@govtnz/ds/build/css/H2.css';
import components__FileUpload from '../../commons/examples/components__FileUpload';
// Indirect relative import because this template is output to src/pages/components so it needs to step back to `commons`.
import ComponentPage from '../../commons/component-page';
import ComponentCode from '../../commons/component-code';
import Example from '../../commons/Example';
import ExampleContainer from '../../commons/ExampleContainer';
import ExampleHeading from '../../commons/ExampleHeading';
import ExampleSection from '../../commons/ExampleSection';

const PageContent = (props) => <React.Fragment><ExampleContainer {...onChangeGenerator(ExampleContainer)}>
    <ExampleHeading {...onChangeGenerator(ExampleHeading)}>Example of File Upload</ExampleHeading>
    <Example {...onChangeGenerator(Example)} code={components__FileUpload[0]} >
        <FileUpload {...onChangeGenerator(FileUpload)} />
        <FileUploadWithErrorMessage {...onChangeGenerator(FileUploadWithErrorMessage)} />
    </Example>
</ExampleContainer>

<H2 {...onChangeGenerator(H2)} styleSize="large" id="credit">Credit</H2>
<p>Original HTML and CSS derived from <a href="https://github.com/alphagov/govuk-frontend">GOV.UK Design System</a>.</p>
</React.Fragment>

export default function Code(props) {
  return (
    <ComponentPage
      title={"FileUpload"}
      id={"FileUpload"}
      pageProps={props}
      PageContent={PageContent}
    />
  );
}
