// @autogenerated

// WARNING THIS FILE IS AUTOGENERATED! DO NOT EDIT!

import React, { Fragment } from 'react';

import FlexContainer from '@govtnz/ds/build/react-ts/FlexContainer.tsx';
import '@govtnz/ds/build/css/FlexContainer.css';
import FlexRow from '@govtnz/ds/build/react-ts/FlexRow.tsx';
import '@govtnz/ds/build/css/FlexRow.css';
import FlexColumn from '@govtnz/ds/build/react-ts/FlexColumn.tsx';
import '@govtnz/ds/build/css/FlexColumn.css';

import IframePage from '../../components/IframePage';
import ExampleContainer from '../../commons/ExampleContainer';
import ExampleHeading from '../../commons/ExampleHeading';
import ExampleSection from '../../commons/ExampleSection';
import onChangeGenerator from '../../commons/onChangeGenerator';
const Example = ({ children }) => <Fragment>{children}</Fragment>;

const PageContent = (props) => (<Example {...onChangeGenerator(Example)}>
        <FlexContainer {...onChangeGenerator(FlexContainer)} width="fixed">
            <FlexRow {...onChangeGenerator(FlexRow)}>
                <FlexColumn {...onChangeGenerator(FlexColumn)} xs="4" sm="4" md="4" lg="4"> .g-flex-col .g-flex-col-md-4 </FlexColumn>
                <FlexColumn {...onChangeGenerator(FlexColumn)} xs="4" sm="4" md="4" lg="4"> .g-flex-col .g-flex-col-md-4 </FlexColumn>
                <FlexColumn {...onChangeGenerator(FlexColumn)} xs="4" sm="4" md="4" lg="4"> .g-flex-col .g-flex-col-md-4 </FlexColumn>
                <FlexColumn {...onChangeGenerator(FlexColumn)} xs="6" sm="6" md="6" lg="6"> .g-flex-col .g-flex-col-md-6 </FlexColumn>
                <FlexColumn {...onChangeGenerator(FlexColumn)} xs="6" sm="6" md="6" lg="6"> .g-flex-col .g-flex-col-md-6 </FlexColumn>
                <FlexColumn {...onChangeGenerator(FlexColumn)} xs="12" sm="12" md="12" lg="12"> .g-flex-col .g-flex-col-lg-12 </FlexColumn>
                <FlexColumn {...onChangeGenerator(FlexColumn)} xs="1" sm="1" md="1" lg="1"> 1/12 </FlexColumn>
                <FlexColumn {...onChangeGenerator(FlexColumn)} xs="11" sm="11" md="11" lg="11"> 11/12 </FlexColumn>
                <FlexColumn {...onChangeGenerator(FlexColumn)} xs="2" sm="2" md="2" lg="2"> 2/12 </FlexColumn>
                <FlexColumn {...onChangeGenerator(FlexColumn)} xs="10" sm="10" md="10" lg="10"> 10/12 </FlexColumn>
                <FlexColumn {...onChangeGenerator(FlexColumn)} xs="3" sm="3" md="3" lg="3"> 3/12 </FlexColumn>
                <FlexColumn {...onChangeGenerator(FlexColumn)} xs="9" sm="9" md="9" lg="9"> 9/12 </FlexColumn>
                <FlexColumn {...onChangeGenerator(FlexColumn)} xs="4" sm="4" md="4" lg="4"> 4/12 </FlexColumn>
                <FlexColumn {...onChangeGenerator(FlexColumn)} xs="8" sm="8" md="8" lg="8"> 8/12 </FlexColumn>
                <FlexColumn {...onChangeGenerator(FlexColumn)} xs="5" sm="5" md="5" lg="5"> 5/12 </FlexColumn>
                <FlexColumn {...onChangeGenerator(FlexColumn)} xs="7" sm="7" md="7" lg="7"> 7/12 </FlexColumn>
                <FlexColumn {...onChangeGenerator(FlexColumn)} xs="6" sm="6" md="6" lg="6"> 6/12 </FlexColumn>
                <FlexColumn {...onChangeGenerator(FlexColumn)} xs="6" sm="6" md="6" lg="6"> 6/12 </FlexColumn>
                <FlexColumn {...onChangeGenerator(FlexColumn)} xs="7" sm="7" md="7" lg="7"> 7/12 </FlexColumn>
                <FlexColumn {...onChangeGenerator(FlexColumn)} xs="5" sm="5" md="5" lg="5"> 5/12 </FlexColumn>
                <FlexColumn {...onChangeGenerator(FlexColumn)} xs="8" sm="8" md="8" lg="8"> 8/12 </FlexColumn>
                <FlexColumn {...onChangeGenerator(FlexColumn)} xs="4" sm="4" md="4" lg="4"> 4/12 </FlexColumn>
                <FlexColumn {...onChangeGenerator(FlexColumn)} xs="9" sm="9" md="9" lg="9"> 9/12 </FlexColumn>
                <FlexColumn {...onChangeGenerator(FlexColumn)} xs="3" sm="3" md="3" lg="3"> 3/12 </FlexColumn>
                <FlexColumn {...onChangeGenerator(FlexColumn)} xs="10" sm="10" md="10" lg="10"> 10/12 </FlexColumn>
                <FlexColumn {...onChangeGenerator(FlexColumn)} xs="2" sm="2" md="2" lg="2"> 2/12 </FlexColumn>
                <FlexColumn {...onChangeGenerator(FlexColumn)} xs="11" sm="11" md="11" lg="11"> 11/12 </FlexColumn>
                <FlexColumn {...onChangeGenerator(FlexColumn)} xs="1" sm="1" md="1" lg="1"> 1/12 </FlexColumn>
            </FlexRow>
        </FlexContainer>
    </Example>);

const template = props => {
  return (
    <IframePage
      title={"Example of Flexgrid column variants"}
      id={"iframe_componentsFlexGrid1"}
      parentUrl={"../FlexGrid"}
      pageProps={props}
      PageContent={PageContent}
    />
  );
};

export default template;
