// @autogenerated

// WARNING THIS FILE IS AUTOGENERATED! DO NOT EDIT!

import React, { Fragment } from 'react';

import H1 from '@govtnz/ds/build/react-ts/H1.tsx';
import '@govtnz/ds/build/css/H1.css';
import CaptionXl from '@govtnz/ds/build/react-ts/CaptionXl.tsx';
import '@govtnz/ds/build/css/CaptionXl.css';

import IframePage from '../../components/IframePage';
import ExampleContainer from '../../commons/ExampleContainer';
import ExampleHeading from '../../commons/ExampleHeading';
import ExampleSection from '../../commons/ExampleSection';
import onChangeGenerator from '../../commons/onChangeGenerator';
const Example = ({ children }) => <Fragment>{children}</Fragment>;

const PageContent = (props) => (<Example {...onChangeGenerator(Example)}>
        <H1 {...onChangeGenerator(H1)} styleSize="xlarge">
            <CaptionXl {...onChangeGenerator(CaptionXl)}>caption-xl</CaptionXl>
            g-heading-xl
        </H1>
    </Example>);

const template = props => {
  return (
    <IframePage
      title={"Example of caption inside heading"}
      id={"iframe_componentsHeadings2"}
      parentUrl={"../Headings"}
      pageProps={props}
      PageContent={PageContent}
    />
  );
};

export default template;
