// @autogenerated

// WARNING THIS FILE IS AUTOGENERATED! DO NOT EDIT!

import React, { Fragment } from 'react';

import FieldsetBlock from '@govtnz/ds/build/react-ts/FieldsetBlock.tsx';
import '@govtnz/ds/build/css/FieldsetBlock.css';
import H1 from '@govtnz/ds/build/react-ts/H1.tsx';
import '@govtnz/ds/build/css/H1.css';
import RadioBlock from '@govtnz/ds/build/react-ts/RadioBlock.tsx';
import '@govtnz/ds/build/css/RadioBlock.css';

import IframePage from '../../components/IframePage';
import ExampleContainer from '../../commons/ExampleContainer';
import ExampleHeading from '../../commons/ExampleHeading';
import ExampleSection from '../../commons/ExampleSection';
import onChangeGenerator from '../../commons/onChangeGenerator';
const Example = ({ children }) => <Fragment>{children}</Fragment>;

const PageContent = (props) => (<Example {...onChangeGenerator(Example)}>
        <FieldsetBlock {...onChangeGenerator(FieldsetBlock)} legend={<H1 {...onChangeGenerator(H1)} styleSize="large" id="whereLiveTitle">Where do you live?</H1>}>
            <RadioBlock {...onChangeGenerator(RadioBlock)} label="North Island" radioId="anyRadioId3334" name="where" value="north" labelId="labelId3" />
            <RadioBlock {...onChangeGenerator(RadioBlock)} label="South Island" radioId="anyRadioId42344" name="where" value="south" labelId="labelId4" />
            <RadioBlock {...onChangeGenerator(RadioBlock)} label="Stewart Island" radioId="anyRadioId5234" name="where" value="stewart" labelId="labelId5" />
            <RadioBlock {...onChangeGenerator(RadioBlock)} label="Chatham Islands" radioId="anyRadioId6234" name="where" value="chatham" labelId="labelId6" />
        </FieldsetBlock>
    </Example>);

const template = props => {
  return (
    <IframePage
      title={"Stacked radio buttons"}
      id={"iframe_componentsRadios2"}
      parentUrl={"../Radios"}
      pageProps={props}
      PageContent={PageContent}
    />
  );
};

export default template;
