// @autogenerated

// WARNING THIS FILE IS AUTOGENERATED! DO NOT EDIT!

import React, { Fragment } from 'react';

import SelectBlock from '@govtnz/ds/build/react-ts/SelectBlock.tsx';
import '@govtnz/ds/build/css/SelectBlock.css';

import IframePage from '../../components/IframePage';
import onChangeGenerator from '../../commons/onChangeGenerator';
const ExampleContainer = ({ children }) => <Fragment>{children}</Fragment>;
const ExampleHeading = ({ children }) => <Fragment>{children}</Fragment>;
const ExampleSection = ({ children }) => <Fragment>{children}</Fragment>;
const Example = ({ children }) => <Fragment>{children}</Fragment>;

const PageContent = (props) => (<Example {...onChangeGenerator(Example)} title="Example of Select">
        <SelectBlock {...onChangeGenerator(SelectBlock)} selectId="select1" label="Order by">
            <option value="published">Recently published</option>
            <option value="updated">Recently updated</option>
            <option value="views">Most views</option>
            <option value="comments">Most comments</option>
        </SelectBlock>
    </Example>);

const template = props => {
  return (
    <IframePage
      title={"Example of Select"}
      id={"iframe_componentsSelect0"}
      parentUrl={"../Select"}
      pageProps={props}
      PageContent={PageContent}
    />
  );
};

export default template;
