// @autogenerated

// WARNING THIS FILE IS AUTOGENERATED! DO NOT EDIT!

import React, { Fragment } from 'react';

import SelectBlock from '@govtnz/ds/build/react-ts/SelectBlock.tsx';
import '@govtnz/ds/build/css/SelectBlock.css';

import IframePage from '../../components/IframePage';
import ExampleContainer from '../../commons/ExampleContainer';
import ExampleHeading from '../../commons/ExampleHeading';
import ExampleSection from '../../commons/ExampleSection';
import onChangeGenerator from '../../commons/onChangeGenerator';
const Example = ({ children }) => <Fragment>{children}</Fragment>;

const PageContent = (props) => (<Example {...onChangeGenerator(Example)}>
        <SelectBlock {...onChangeGenerator(SelectBlock)} selectId="select1" label="Order by">
            <option value="published">Recently published</option>
            <option value="updated">Recently updated</option>
            <option value="views">Most views</option>
            <option value="comments">Most comments</option>
        </SelectBlock>
    </Example>);

const template = props => {
  return (
    <IframePage
      title={"Example 0"}
      id={"iframe_componentsSelect0"}
      parentUrl={"../Select"}
      pageProps={props}
      PageContent={PageContent}
    />
  );
};

export default template;
