// @autogenerated

// WARNING THIS FILE IS AUTOGENERATED! DO NOT EDIT!

import React, { Fragment } from 'react';
import ReactDOM from 'react-dom';

import P from '@govtnz/ds/build/react-ts/P.tsx';import Ul from '@govtnz/ds/build/react-ts/Ul.tsx';import Li from '@govtnz/ds/build/react-ts/Li.tsx';
const onChangeGenerator = comp => ({});
const ExampleContainer = ({ children }) => <Fragment>{children}</Fragment>;
const ExampleHeading = ({ children }) => <Fragment>{children}</Fragment>;
const ExampleSection = ({ children }) => (
  <div className="example__section">{children}</div>
);
const Example = ({ children }) => <Fragment>{children}</Fragment>;

var PageContent = (props) => (<Example {...onChangeGenerator(Example)}><P styleSize="medium">To help keep the kitchen clean, please:</P>

<Ul {...onChangeGenerator(Ul)} bulleted>
    <Li {...onChangeGenerator(Li)}>replace tea and coffee jars on shelf</Li>
    <Li {...onChangeGenerator(Li)}>wipe down bench</Li>
    <Li {...onChangeGenerator(Li)}>wash dishes by: <Ul {...onChangeGenerator(Ul)} bulleted>
            <Li {...onChangeGenerator(Li)}>loading the dishwasher, if it's empty</Li>
            <Li {...onChangeGenerator(Li)}>rinsing and stacking, if dishwasher is going</Li>
        </Ul>
    </Li>
    <Li {...onChangeGenerator(Li)}>put recycling in labelled bins</Li>
</Ul>
</Example>);

    document.addEventListener('DOMContentLoaded', () => {
      const selector = '#root';
      const root = document.querySelector(selector);
      if (!root) {
        console.error("Couldn't find app mount point ", selector);
        return;
      }
      ReactDOM.hydrate(<PageContent />, root, window.afterRender);
    });
    