// @autogenerated

// WARNING THIS FILE IS AUTOGENERATED! DO NOT EDIT!

import React, { Fragment } from 'react';

import CaptionXl from '@govtnz/ds/build/react-ts/CaptionXl.tsx';
import '@govtnz/ds/build/css/CaptionXl.css';
import H1 from '@govtnz/ds/build/react-ts/H1.tsx';
import '@govtnz/ds/build/css/H1.css';
import CaptionL from '@govtnz/ds/build/react-ts/CaptionL.tsx';
import '@govtnz/ds/build/css/CaptionL.css';
import H2 from '@govtnz/ds/build/react-ts/H2.tsx';
import '@govtnz/ds/build/css/H2.css';
import CaptionM from '@govtnz/ds/build/react-ts/CaptionM.tsx';
import '@govtnz/ds/build/css/CaptionM.css';
import H3 from '@govtnz/ds/build/react-ts/H3.tsx';
import '@govtnz/ds/build/css/H3.css';

import IframePage from '../../components/IframePage';
import onChangeGenerator from '../../commons/onChangeGenerator';
const ExampleContainer = ({ children }) => <Fragment>{children}</Fragment>;
const ExampleHeading = ({ children }) => <Fragment>{children}</Fragment>;
const ExampleSection = ({ children }) => <Fragment>{children}</Fragment>;
const Example = ({ children }) => <Fragment>{children}</Fragment>;

const PageContent = (props) => (<Example {...onChangeGenerator(Example)}>
        <ExampleSection {...onChangeGenerator(ExampleSection)}>
            <CaptionXl {...onChangeGenerator(CaptionXl)}>caption-xl</CaptionXl>
            <H1 {...onChangeGenerator(H1)} styleSize="xlarge">g-heading-xl</H1>
        </ExampleSection>
        <ExampleSection {...onChangeGenerator(ExampleSection)}>
            <CaptionL {...onChangeGenerator(CaptionL)}>caption-l</CaptionL>
            <H2 {...onChangeGenerator(H2)} styleSize="large">g-heading-l</H2>
        </ExampleSection>
        <ExampleSection {...onChangeGenerator(ExampleSection)}>
            <CaptionM {...onChangeGenerator(CaptionM)}>caption-m</CaptionM>
            <H3 {...onChangeGenerator(H3)} styleSize="medium">g-heading-m</H3>
        </ExampleSection>
    </Example>);

const template = props => {
  return (
    <IframePage
      title={"Headings with captions"}
      id={"iframe_basicstypography2"}
      parentUrl={"../typography"}
      pageProps={props}
      PageContent={PageContent}
    />
  );
};

export default template;
