// @autogenerated

// WARNING THIS FILE IS AUTOGENERATED! DO NOT EDIT!

import React, { Fragment } from 'react';

import H1 from '@govtnz/ds/build/react-ts/H1.tsx';
import '@govtnz/ds/build/css/H1.css';
import H2 from '@govtnz/ds/build/react-ts/H2.tsx';
import '@govtnz/ds/build/css/H2.css';
import H3 from '@govtnz/ds/build/react-ts/H3.tsx';
import '@govtnz/ds/build/css/H3.css';
import H4 from '@govtnz/ds/build/react-ts/H4.tsx';
import '@govtnz/ds/build/css/H4.css';
import H5 from '@govtnz/ds/build/react-ts/H5.tsx';
import '@govtnz/ds/build/css/H5.css';
import H6 from '@govtnz/ds/build/react-ts/H6.tsx';
import '@govtnz/ds/build/css/H6.css';

import IframePage from '../../components/IframePage';
import ExampleContainer from '../../commons/ExampleContainer';
import ExampleHeading from '../../commons/ExampleHeading';
import ExampleSection from '../../commons/ExampleSection';
import onChangeGenerator from '../../commons/onChangeGenerator';
const Example = ({ children }) => <Fragment>{children}</Fragment>;

const PageContent = (props) => (<Example {...onChangeGenerator(Example)}>
        <ExampleSection {...onChangeGenerator(ExampleSection)}>
            <H1 {...onChangeGenerator(H1)} styleSize="xlarge">g-heading-xl</H1>
        </ExampleSection>
        <ExampleSection {...onChangeGenerator(ExampleSection)}>
            <H2 {...onChangeGenerator(H2)} styleSize="large">g-heading-l</H2>
        </ExampleSection>
        <ExampleSection {...onChangeGenerator(ExampleSection)}>
            <H3 {...onChangeGenerator(H3)} styleSize="medium">g-heading-m</H3>
        </ExampleSection>
        <ExampleSection {...onChangeGenerator(ExampleSection)}>
            <H4 {...onChangeGenerator(H4)} styleSize="small">g-heading-s</H4>
        </ExampleSection>
        <ExampleSection {...onChangeGenerator(ExampleSection)}>
            <H5 {...onChangeGenerator(H5)} styleSize="xsmall">g-heading-xs</H5>
        </ExampleSection>
        <ExampleSection {...onChangeGenerator(ExampleSection)}>
            <H6 {...onChangeGenerator(H6)} styleSize="xxsmall">g-heading-xxs</H6>
        </ExampleSection>
    </Example>);

const template = props => {
  return (
    <IframePage
      title={"Example 0"}
      id={"iframe_basicstypography0"}
      parentUrl={"../typography"}
      pageProps={props}
      PageContent={PageContent}
    />
  );
};

export default template;
