// @autogenerated

// WARNING THIS FILE IS AUTOGENERATED! DO NOT EDIT!

import React, { Fragment } from 'react';

import H3 from '@govtnz/ds/build/react-ts/H3.tsx';
import '@govtnz/ds/build/css/H3.css';

import IframePage from '../../components/IframePage';
import onChangeGenerator from '../../commons/onChangeGenerator';
const ExampleContainer = ({ children }) => <Fragment>{children}</Fragment>;
const ExampleHeading = ({ children }) => <Fragment>{children}</Fragment>;
const ExampleSection = ({ children }) => <Fragment>{children}</Fragment>;
const Example = ({ children }) => <Fragment>{children}</Fragment>;

const PageContent = (props) => (<Example {...onChangeGenerator(Example)}>
        <ExampleSection {...onChangeGenerator(ExampleSection)}>
            <H3 {...onChangeGenerator(H3)} styleSize="xlarge">H3 g-heading-xl</H3>
        </ExampleSection>
        <ExampleSection {...onChangeGenerator(ExampleSection)}>
            <H3 {...onChangeGenerator(H3)} styleSize="large">H3 g-heading-l</H3>
        </ExampleSection>
        <ExampleSection {...onChangeGenerator(ExampleSection)}>
            <H3 {...onChangeGenerator(H3)} styleSize="medium">H3 g-heading-m</H3>
        </ExampleSection>
        <ExampleSection {...onChangeGenerator(ExampleSection)}>
            <H3 {...onChangeGenerator(H3)} styleSize="small">H3 g-heading-s</H3>
        </ExampleSection>
        <ExampleSection {...onChangeGenerator(ExampleSection)}>
            <H3 {...onChangeGenerator(H3)} styleSize="xsmall">H3 g-heading-xs</H3>
        </ExampleSection>
        <ExampleSection {...onChangeGenerator(ExampleSection)}>
            <H3 {...onChangeGenerator(H3)} styleSize="xxsmall">H3 g-heading-xxs</H3>
        </ExampleSection>
    </Example>);

const template = props => {
  return (
    <IframePage
      title={"Same heading level varying by size only"}
      id={"iframe_basicstypography1"}
      parentUrl={"../typography"}
      pageProps={props}
      PageContent={PageContent}
    />
  );
};

export default template;
