// @autogenerated


export default [
  {
    "mustache": "// Developer note: ensure your \".mustache\" files are imported as plain text. In Webpack you might use https://github.com/webpack-contrib/raw-loader\nimport Mustache from \"mustache\";\nimport Button from \"@govtnz/ds/build/mustache/Button.mustache\";\n\n// The variables Button are all strings that are mustache templates.\n\nexport default `${Mustache.render(Button, {\n  type: `Button`,\n  children: `Some text`\n})}`;\n",
    "silverstripe-components": "",
    "react-js": "import React from \"react\";\nimport Button from \"@govtnz/ds/build/react-js/Button\";\nimport \"@govtnz/ds/build/css/Button.css\"; // or @govtnz/ds/build/scss/Button.scss\n\nexport default () => <Button type=\"Button\">Some text</Button>;\n",
    "react-ts": "import * as React from \"react\";\nimport * as Button from \"@govtnz/ds/build/react-ts/Button\";\nimport \"@govtnz/ds/build/css/Button.css\"; // or @govtnz/ds/build/scss/Button.scss\n\nexport default () => <Button type=\"Button\">Some text</Button>;\n",
    "react-js-styled-components": "import React from \"react\";\nimport Button from \"@govtnz/ds/build/react-js-styled-components/Button\";\n\nexport default () => <Button type=\"Button\">Some text</Button>;\n",
    "react-ts-styled-components": "import * as React from \"react\";\nimport * as Button from \"@govtnz/ds/build/react-ts-styled-components/Button\";\n\nexport default () => <Button type=\"Button\">Some text</Button>;\n",
    "vue-js": "<template>\n  <c-button type=\"Button\">\n    Some text\n  </c-button>\n</template>\n<script>\nimport Vue from \"vue\";\nimport Button from \"@govtnz/ds/build/vue-js/Button\";\n\nexport default { components: { \"c-button\": Button } };\n</script>\n",
    "vue-ts": "<template>\n  <c-button type=\"Button\">\n    Some text\n  </c-button>\n</template>\n<script lang=\"ts\">\nimport Vue from \"vue\";\nimport Button from \"@govtnz/ds/build/vue-ts/Button\";\n\nexport default { components: { \"c-button\": Button } };\n</script>\n",
    "scss": "",
    "html": "<!--\nRemember to add these styles:\nin CSS: Button.css\nOR in Sass (SCSS): Button.scss\n-->\n<button class=\"g-button\" type=\"button\">Some text</button>\n",
    "css": "",
    "twig-embed": "{% embed \"Button.html.twig\"  with {'type':'Button', 'children':'Some text'} only %}{% endembed %}"
  },
  {
    "mustache": "// Developer note: ensure your \".mustache\" files are imported as plain text. In Webpack you might use https://github.com/webpack-contrib/raw-loader\nimport Mustache from \"mustache\";\nimport Button from \"@govtnz/ds/build/mustache/Button.mustache\";\n\n// The variables Button are all strings that are mustache templates.\n\nexport default `${Mustache.render(Button, {\n  type: `Button`,\n  disabled: true,\n  children: `Some text`\n})}`;\n",
    "silverstripe-components": "",
    "react-js": "import React from \"react\";\nimport Button from \"@govtnz/ds/build/react-js/Button\";\nimport \"@govtnz/ds/build/css/Button.css\"; // or @govtnz/ds/build/scss/Button.scss\n\nexport default () => (\n  <Button type=\"Button\" disabled>\n    Some text\n  </Button>\n);\n",
    "react-ts": "import * as React from \"react\";\nimport * as Button from \"@govtnz/ds/build/react-ts/Button\";\nimport \"@govtnz/ds/build/css/Button.css\"; // or @govtnz/ds/build/scss/Button.scss\n\nexport default () => (\n  <Button type=\"Button\" disabled>\n    Some text\n  </Button>\n);\n",
    "react-js-styled-components": "import React from \"react\";\nimport Button from \"@govtnz/ds/build/react-js-styled-components/Button\";\n\nexport default () => (\n  <Button type=\"Button\" disabled>\n    Some text\n  </Button>\n);\n",
    "react-ts-styled-components": "import * as React from \"react\";\nimport * as Button from \"@govtnz/ds/build/react-ts-styled-components/Button\";\n\nexport default () => (\n  <Button type=\"Button\" disabled>\n    Some text\n  </Button>\n);\n",
    "vue-js": "<template>\n  <c-button type=\"Button\" disabled>\n    Some text\n  </c-button>\n</template>\n<script>\nimport Vue from \"vue\";\nimport Button from \"@govtnz/ds/build/vue-js/Button\";\n\nexport default { components: { \"c-button\": Button } };\n</script>\n",
    "vue-ts": "<template>\n  <c-button type=\"Button\" disabled>\n    Some text\n  </c-button>\n</template>\n<script lang=\"ts\">\nimport Vue from \"vue\";\nimport Button from \"@govtnz/ds/build/vue-ts/Button\";\n\nexport default { components: { \"c-button\": Button } };\n</script>\n",
    "scss": "",
    "html": "<!--\nRemember to add these styles:\nin CSS: Button.css\nOR in Sass (SCSS): Button.scss\n-->\n<button\n  class=\"g-button g-button--disabled\"\n  type=\"button\"\n  aria-disabled\n  disabled\n>\n  Some text\n</button>\n",
    "css": "",
    "twig-embed": "{% embed \"Button.html.twig\"  with {'type':'Button', 'disabled':'true', 'children':'Some text'} only %}{% endembed %}"
  }
]