// @autogenerated


export default [
  {
    "mustache": "// Developer note: ensure your \".mustache\" files are imported as plain text. In Webpack you might use https://github.com/webpack-contrib/raw-loader\nimport Mustache from \"mustache\";\nimport FieldsetBlock from \"@govtnz/ds/build/mustache/FieldsetBlock.mustache\";\n\n// The variables FieldsetBlock are all strings that are mustache templates.\n\nexport default `${Mustache.render(FieldsetBlock, {\n  id: `addressId`,\n  legend: `Legend`\n})}`;\n",
    "silverstripe-components": "",
    "react-js": "import React from \"react\";\nimport FieldsetBlock from \"@govtnz/ds/build/react-js/FieldsetBlock\";\nimport \"@govtnz/ds/build/css/FieldsetBlock.css\"; // or @govtnz/ds/build/scss/FieldsetBlock.scss\n\nexport default () => <FieldsetBlock id=\"addressId\" legend=\"Legend\" />;\n",
    "react-ts": "import * as React from \"react\";\nimport * as FieldsetBlock from \"@govtnz/ds/build/react-ts/FieldsetBlock\";\nimport \"@govtnz/ds/build/css/FieldsetBlock.css\"; // or @govtnz/ds/build/scss/FieldsetBlock.scss\n\nexport default () => <FieldsetBlock id=\"addressId\" legend=\"Legend\" />;\n",
    "react-js-styled-components": "import React from \"react\";\nimport FieldsetBlock from \"@govtnz/ds/build/react-js-styled-components/FieldsetBlock\";\n\nexport default () => <FieldsetBlock id=\"addressId\" legend=\"Legend\" />;\n",
    "react-ts-styled-components": "import * as React from \"react\";\nimport * as FieldsetBlock from \"@govtnz/ds/build/react-ts-styled-components/FieldsetBlock\";\n\nexport default () => <FieldsetBlock id=\"addressId\" legend=\"Legend\" />;\n",
    "vue-js": "<template>\n  <fieldset-block id=\"addressId\" legend=\"Legend\" />\n</template>\n<script>\nimport Vue from \"vue\";\nimport FieldsetBlock from \"@govtnz/ds/build/vue-js/FieldsetBlock.vue\";\n\nexport default { components: { \"fieldset-block\": FieldsetBlock } };\n</script>\n",
    "vue-ts": "<template>\n  <fieldset-block id=\"addressId\" legend=\"Legend\" />\n</template>\n<script lang=\"ts\">\nimport Vue from \"vue\";\nimport FieldsetBlock from \"@govtnz/ds/build/vue-ts/FieldsetBlock.vue\";\n\nexport default { components: { \"fieldset-block\": FieldsetBlock } };\n</script>\n",
    "scss": "",
    "html": "<!--\nRemember to add these styles:\nin CSS: FieldsetBlock.css\nOR in Sass (SCSS): FieldsetBlock.scss\n-->\n<div class=\"g-fieldsetBlock-form-group\">\n  <fieldset class=\"g-fieldset\">\n    <legend class=\"g-fieldset__legend\">Legend</legend>\n    <div>Fieldset contents</div>\n  </fieldset>\n</div>\n",
    "css": "",
    "twig-embed": "{% embed \"FieldsetBlock.html.twig\"  with {'id':'addressId', 'legend':'Legend'} only %}{% endembed %}",
    "angular": ""
  },
  {
    "mustache": "// Developer note: ensure your \".mustache\" files are imported as plain text. In Webpack you might use https://github.com/webpack-contrib/raw-loader\nimport Mustache from \"mustache\";\nimport FieldsetBlock from \"@govtnz/ds/build/mustache/FieldsetBlock.mustache\";\nimport H1 from \"@govtnz/ds/build/mustache/H1.mustache\";\n\n// The variables FieldsetBlock, H1 are all strings that are mustache templates.\n\nexport default `${Mustache.render(FieldsetBlock, {\n  id: `addressId`,\n  legend: `${Mustache.render(H1, {\n    \"styleSize=large\": true,\n    styleSize: true,\n    children: `Page heading`\n  })}`\n})}`;\n",
    "silverstripe-components": "",
    "react-js": "import React from \"react\";\nimport FieldsetBlock from \"@govtnz/ds/build/react-js/FieldsetBlock\";\nimport \"@govtnz/ds/build/css/FieldsetBlock.css\"; // or @govtnz/ds/build/scss/FieldsetBlock.scss\nimport H1 from \"@govtnz/ds/build/react-js/H1\";\nimport \"@govtnz/ds/build/css/H1.css\"; // or @govtnz/ds/build/scss/H1.scss\n\nexport default () => (\n  <FieldsetBlock\n    id=\"addressId\"\n    legend={<H1 styleSize=\"large\">Page heading</H1>}\n  />\n);\n",
    "react-ts": "import * as React from \"react\";\nimport * as FieldsetBlock from \"@govtnz/ds/build/react-ts/FieldsetBlock\";\nimport \"@govtnz/ds/build/css/FieldsetBlock.css\"; // or @govtnz/ds/build/scss/FieldsetBlock.scss\nimport * as H1 from \"@govtnz/ds/build/react-ts/H1\";\nimport \"@govtnz/ds/build/css/H1.css\"; // or @govtnz/ds/build/scss/H1.scss\n\nexport default () => (\n  <FieldsetBlock\n    id=\"addressId\"\n    legend={<H1 styleSize=\"large\">Page heading</H1>}\n  />\n);\n",
    "react-js-styled-components": "import React from \"react\";\nimport FieldsetBlock from \"@govtnz/ds/build/react-js-styled-components/FieldsetBlock\";\nimport H1 from \"@govtnz/ds/build/react-js-styled-components/H1\";\n\nexport default () => (\n  <FieldsetBlock\n    id=\"addressId\"\n    legend={<H1 styleSize=\"large\">Page heading</H1>}\n  />\n);\n",
    "react-ts-styled-components": "import * as React from \"react\";\nimport * as FieldsetBlock from \"@govtnz/ds/build/react-ts-styled-components/FieldsetBlock\";\nimport * as H1 from \"@govtnz/ds/build/react-ts-styled-components/H1\";\n\nexport default () => (\n  <FieldsetBlock\n    id=\"addressId\"\n    legend={<H1 styleSize=\"large\">Page heading</H1>}\n  />\n);\n",
    "vue-js": "<template>\n  <fieldset-block id=\"addressId\" legend=\"Page heading\" />\n</template>\n<script>\nimport Vue from \"vue\";\nimport FieldsetBlock from \"@govtnz/ds/build/vue-js/FieldsetBlock.vue\";\nimport H1 from \"@govtnz/ds/build/vue-js/H1.vue\";\n\nexport default { components: { \"fieldset-block\": FieldsetBlock, \"c-h1\": H1 } };\n</script>\n",
    "vue-ts": "<template>\n  <fieldset-block id=\"addressId\" legend=\"Page heading\" />\n</template>\n<script lang=\"ts\">\nimport Vue from \"vue\";\nimport FieldsetBlock from \"@govtnz/ds/build/vue-ts/FieldsetBlock.vue\";\nimport H1 from \"@govtnz/ds/build/vue-ts/H1.vue\";\n\nexport default { components: { \"fieldset-block\": FieldsetBlock, \"c-h1\": H1 } };\n</script>\n",
    "scss": "",
    "html": "<!--\nRemember to add these styles:\nin CSS: FieldsetBlock.css, H1.css\nOR in Sass (SCSS): FieldsetBlock.scss, H1.scss\n-->\n<div class=\"g-fieldsetBlock-form-group\">\n  <fieldset class=\"g-fieldset\">\n    <legend class=\"g-fieldset__legend\">\n      <h1 class=\"g-heading-l\">Page heading</h1>\n    </legend>\n    <div>Fieldset contents</div>\n  </fieldset>\n</div>\n",
    "css": "",
    "twig-embed": "{% embed \"FieldsetBlock.html.twig\"  with {'id':'addressId'} only %}{% block legend %}{% embed \"H1.html.twig\"  with {'styleSize':'large', 'children':'Page heading'} only %}{% endembed %}{% endblock %}{% endembed %}",
    "angular": ""
  }
]