// @autogenerated


export default [
  {
    "mustache": "// Developer note: ensure your \".mustache\" files are imported as plain text. In Webpack you might use https://github.com/webpack-contrib/raw-loader\nimport Mustache from \"mustache\";\nimport Breadcrumbs from \"@govtnz/ds/build/mustache/Breadcrumbs.mustache\";\n\n// The variables Breadcrumbs are all strings that are mustache templates.\n\nexport default `${Mustache.render(Breadcrumbs, {})}`;\n",
    "silverstripe-components": "",
    "react-js": "import React from \"react\";\nimport Breadcrumbs from \"@govtnz/ds/build/react-js/Breadcrumbs\";\nimport \"@govtnz/ds/build/css/Breadcrumbs.css\"; // or @govtnz/ds/build/scss/Breadcrumbs.scss\n\nexport default () => <Breadcrumbs />;\n",
    "react-ts": "import * as React from \"react\";\nimport * as Breadcrumbs from \"@govtnz/ds/build/react-ts/Breadcrumbs\";\nimport \"@govtnz/ds/build/css/Breadcrumbs.css\"; // or @govtnz/ds/build/scss/Breadcrumbs.scss\n\nexport default () => <Breadcrumbs />;\n",
    "react-js-styled-components": "import React from \"react\";\nimport Breadcrumbs from \"@govtnz/ds/build/react-js-styled-components/Breadcrumbs\";\n\nexport default () => <Breadcrumbs />;\n",
    "react-ts-styled-components": "import * as React from \"react\";\nimport * as Breadcrumbs from \"@govtnz/ds/build/react-ts-styled-components/Breadcrumbs\";\n\nexport default () => <Breadcrumbs />;\n",
    "vue-js": "<template>\n  <c-breadcrumbs />\n</template>\n<script>\nimport Vue from \"vue\";\nimport Breadcrumbs from \"@govtnz/ds/build/vue-js/Breadcrumbs\";\n\nexport default { components: { \"c-breadcrumbs\": Breadcrumbs } };\n</script>\n",
    "vue-ts": "<template>\n  <c-breadcrumbs />\n</template>\n<script lang=\"ts\">\nimport Vue from \"vue\";\nimport Breadcrumbs from \"@govtnz/ds/build/vue-ts/Breadcrumbs\";\n\nexport default { components: { \"c-breadcrumbs\": Breadcrumbs } };\n</script>\n",
    "scss": "",
    "html": "<!--\nRemember to add these styles:\nin CSS: Breadcrumbs.css\nOR in Sass (SCSS): Breadcrumbs.scss\n-->\n<div class=\"g-breadcrumbs\">\n  <ol class=\"g-breadcrumbs__list\">\n    <li class=\"g-breadcrumbs__list-item\">\n      <a class=\"g-breadcrumbs__link\"> Section</a>\n    </li>\n    <li class=\"g-breadcrumbs__list-item\">\n      <a class=\"g-breadcrumbs__link\"> Sub-section</a>\n    </li>\n  </ol>\n</div>\n",
    "css": "",
    "twig-embed": "{% embed \"Breadcrumbs.html.twig\" %}{% endembed %}"
  }
]