// @autogenerated


export default [
  {
    "mustache": "// Developer note: ensure your \".mustache\" files are imported as plain text. In Webpack you might use https://github.com/webpack-contrib/raw-loader\nimport Mustache from \"mustache\";\nimport Footer from \"@govtnz/ds/build/mustache/Footer.mustache\";\n\n// The variables Footer are all strings that are mustache templates.\n\nexport default `${Mustache.render(Footer, {\n  children: `<p >Footer content goes here.</p>`\n})}`;\n",
    "silverstripe-components": "",
    "react-js": "import React from \"react\";\nimport Footer from \"@govtnz/ds/build/react-js/Footer\";\nimport \"@govtnz/ds/build/css/Footer.css\"; // or @govtnz/ds/build/scss/Footer.scss\n\nexport default () => (\n  <Footer>\n    <p>Footer content goes here.</p>\n  </Footer>\n);\n",
    "react-ts": "import React from \"react\";\nimport Footer from \"@govtnz/ds/build/react-ts/Footer\";\nimport \"@govtnz/ds/build/css/Footer.css\"; // or @govtnz/ds/build/scss/Footer.scss\n\nexport default () => (\n  <Footer>\n    <p>Footer content goes here.</p>\n  </Footer>\n);\n",
    "react-js-styled-components": "import React from \"react\";\nimport Footer from \"@govtnz/ds/build/react-js-styled-components/Footer\";\n\nexport default () => (\n  <Footer>\n    <p>Footer content goes here.</p>\n  </Footer>\n);\n",
    "react-ts-styled-components": "import React from \"react\";\nimport Footer from \"@govtnz/ds/build/react-ts-styled-components/Footer\";\n\nexport default () => (\n  <Footer>\n    <p>Footer content goes here.</p>\n  </Footer>\n);\n",
    "vue-js": "<template>\n  <c-footer>\n    <p>\n      Footer content goes here.\n    </p>\n  </c-footer>\n</template>\n<script>\nimport Vue from \"vue\";\nimport Footer from \"@govtnz/ds/build/vue-js/Footer.vue\";\n\nexport default { components: { \"c-footer\": Footer } };\n</script>\n",
    "vue-ts": "<template>\n  <c-footer>\n    <p>\n      Footer content goes here.\n    </p>\n  </c-footer>\n</template>\n<script lang=\"ts\">\nimport Vue from \"vue\";\nimport Footer from \"@govtnz/ds/build/vue-ts/Footer.vue\";\n\nexport default { components: { \"c-footer\": Footer } };\n</script>\n",
    "scss": "",
    "html": "<!--\nRemember to add these styles:\nin CSS: Footer.css\nOR in Sass (SCSS): Footer.scss\n-->\n<footer role=\"contentinfo\" class=\"g-footer\">\n  <p>Footer content goes here.</p>\n</footer>\n",
    "css": "",
    "twig-embed": "{% embed \"Footer.html.twig\" %}{% block children %}<p >Footer content goes here.</p>{% endblock %}{% endembed %}",
    "angular": ""
  }
]