// @autogenerated


export default [
  {
    "mustache": "// Developer note: ensure your \".mustache\" files are imported as plain text. In Webpack you might use https://github.com/webpack-contrib/raw-loader\nimport Mustache from \"mustache\";\nimport BackLinkWithCustomText from \"@govtnz/ds/build/mustache/BackLinkWithCustomText.mustache\";\n\n// The variables BackLinkWithCustomText are all strings that are mustache templates.\n\nexport default `${Mustache.render(BackLinkWithCustomText, {})}`;\n",
    "silverstripe-components": "",
    "react-js": "import React from \"react\";\nimport BackLinkWithCustomText from \"@govtnz/ds/build/react-js/BackLinkWithCustomText\";\nimport \"@govtnz/ds/build/css/BackLinkWithCustomText.css\"; // or @govtnz/ds/build/scss/BackLinkWithCustomText.scss\n\nexport default () => <BackLinkWithCustomText />;\n",
    "react-ts": "import * as React from \"react\";\nimport * as BackLinkWithCustomText from \"@govtnz/ds/build/react-ts/BackLinkWithCustomText\";\nimport \"@govtnz/ds/build/css/BackLinkWithCustomText.css\"; // or @govtnz/ds/build/scss/BackLinkWithCustomText.scss\n\nexport default () => <BackLinkWithCustomText />;\n",
    "react-js-styled-components": "import React from \"react\";\nimport BackLinkWithCustomText from \"@govtnz/ds/build/react-js-styled-components/BackLinkWithCustomText\";\n\nexport default () => <BackLinkWithCustomText />;\n",
    "react-ts-styled-components": "import * as React from \"react\";\nimport * as BackLinkWithCustomText from \"@govtnz/ds/build/react-ts-styled-components/BackLinkWithCustomText\";\n\nexport default () => <BackLinkWithCustomText />;\n",
    "vue-js": "<template>\n  <back-link-with-custom-text />\n</template>\n<script>\nimport Vue from \"vue\";\nimport BackLinkWithCustomText from \"@govtnz/ds/build/vue-js/BackLinkWithCustomText\";\n\nexport default {\n  components: { \"back-link-with-custom-text\": BackLinkWithCustomText }\n};\n</script>\n",
    "vue-ts": "<template>\n  <back-link-with-custom-text />\n</template>\n<script lang=\"ts\">\nimport Vue from \"vue\";\nimport BackLinkWithCustomText from \"@govtnz/ds/build/vue-ts/BackLinkWithCustomText\";\n\nexport default {\n  components: { \"back-link-with-custom-text\": BackLinkWithCustomText }\n};\n</script>\n",
    "scss": "",
    "html": "<!--\nRemember to add these styles:\nin CSS: BackLinkWithCustomText.css\nOR in Sass (SCSS): BackLinkWithCustomText.scss\n-->\n<a class=\"g-backLinkWithCustomText-back-link\"> Example text </a>\n",
    "css": "",
    "twig-embed": "{% embed \"BackLinkWithCustomText.html.twig\" %}{% endembed %}"
  }
]