// @autogenerated


export default [
  {
    "mustache": "// Developer note: ensure your \".mustache\" files are imported as plain text. In Webpack you might use https://github.com/webpack-contrib/raw-loader\nimport Mustache from \"mustache\";\nimport P from \"@govtnz/ds/build/mustache/P.mustache\";\nimport A from \"@govtnz/ds/build/mustache/A.mustache\";\n\n// The variables P, A are all strings that are mustache templates.\n\nexport default `${Mustache.render(P, {\n  \"styleSize=medium\": true,\n  styleSize: true,\n  children: `${Mustache.render(A, {\n    href: `http://example.com/`,\n    children: `Normal link`\n  })}`\n})}`;\n",
    "silverstripe-components": "",
    "react-js": "import React from \"react\";\nimport P from \"@govtnz/ds/build/react-js/P\";\nimport \"@govtnz/ds/build/css/P.css\"; // or @govtnz/ds/build/scss/P.scss\nimport A from \"@govtnz/ds/build/react-js/A\";\nimport \"@govtnz/ds/build/css/A.css\"; // or @govtnz/ds/build/scss/A.scss\n\nexport default () => (\n  <P styleSize=\"medium\">\n    <A href=\"http://example.com/\">Normal link</A>\n  </P>\n);\n",
    "react-ts": "import React from \"react\";\nimport P from \"@govtnz/ds/build/react-ts/P\";\nimport \"@govtnz/ds/build/css/P.css\"; // or @govtnz/ds/build/scss/P.scss\nimport A from \"@govtnz/ds/build/react-ts/A\";\nimport \"@govtnz/ds/build/css/A.css\"; // or @govtnz/ds/build/scss/A.scss\n\nexport default () => (\n  <P styleSize=\"medium\">\n    <A href=\"http://example.com/\">Normal link</A>\n  </P>\n);\n",
    "react-js-styled-components": "import React from \"react\";\nimport P from \"@govtnz/ds/build/react-js-styled-components/P\";\nimport A from \"@govtnz/ds/build/react-js-styled-components/A\";\n\nexport default () => (\n  <P styleSize=\"medium\">\n    <A href=\"http://example.com/\">Normal link</A>\n  </P>\n);\n",
    "react-ts-styled-components": "import React from \"react\";\nimport P from \"@govtnz/ds/build/react-ts-styled-components/P\";\nimport A from \"@govtnz/ds/build/react-ts-styled-components/A\";\n\nexport default () => (\n  <P styleSize=\"medium\">\n    <A href=\"http://example.com/\">Normal link</A>\n  </P>\n);\n",
    "vue-js": "<template>\n  <c-p styleSize=\"medium\">\n    <c-a href=\"http://example.com/\">\n      Normal link\n    </c-a>\n  </c-p>\n</template>\n<script>\nimport Vue from \"vue\";\nimport P from \"@govtnz/ds/build/vue-js/P.vue\";\nimport A from \"@govtnz/ds/build/vue-js/A.vue\";\n\nexport default { components: { \"c-p\": P, \"c-a\": A } };\n</script>\n",
    "vue-ts": "<template>\n  <c-p styleSize=\"medium\">\n    <c-a href=\"http://example.com/\">\n      Normal link\n    </c-a>\n  </c-p>\n</template>\n<script lang=\"ts\">\nimport Vue from \"vue\";\nimport P from \"@govtnz/ds/build/vue-ts/P.vue\";\nimport A from \"@govtnz/ds/build/vue-ts/A.vue\";\n\nexport default { components: { \"c-p\": P, \"c-a\": A } };\n</script>\n",
    "scss": "",
    "html": "<!--\nRemember to add these styles:\nin CSS: P.css, A.css\nOR in Sass (SCSS): P.scss, A.scss\n-->\n<p class=\"g-body-m\">\n  <a class=\"g-link\" href=\"http://example.com/\"> Normal link </a>\n</p>\n",
    "css": "",
    "twig-embed": "{% embed \"P.html.twig\"  with {'styleSize':'medium'} only %}{% block children %}{% embed \"A.html.twig\"  with {'href':'http://example.com/', 'children':'Normal link'} only %}{% endembed %}{% endblock %}{% endembed %}",
    "angular": ""
  }
]