// @autogenerated


export default [
  {
    "mustache": "// Developer note: ensure your \".mustache\" files are imported as plain text. In Webpack you might use https://github.com/webpack-contrib/raw-loader\nimport Mustache from \"mustache\";\nimport CharacterCountWithCustomRows from \"@govtnz/ds/build/mustache/CharacterCountWithCustomRows.mustache\";\n\n// The variables CharacterCountWithCustomRows are all strings that are mustache templates.\n\nexport default `${Mustache.render(CharacterCountWithCustomRows, {\n  maxLength: `200`\n})}`;\n",
    "silverstripe-components": "",
    "react-js": "import React from \"react\";\nimport CharacterCountWithCustomRows from \"@govtnz/ds/build/react-js/CharacterCountWithCustomRows\";\nimport \"@govtnz/ds/build/css/CharacterCountWithCustomRows.css\"; // or @govtnz/ds/build/scss/CharacterCountWithCustomRows.scss\n\nexport default () => <CharacterCountWithCustomRows maxLength=\"200\" />;\n",
    "react-ts": "import * as React from \"react\";\nimport * as CharacterCountWithCustomRows from \"@govtnz/ds/build/react-ts/CharacterCountWithCustomRows\";\nimport \"@govtnz/ds/build/css/CharacterCountWithCustomRows.css\"; // or @govtnz/ds/build/scss/CharacterCountWithCustomRows.scss\n\nexport default () => <CharacterCountWithCustomRows maxLength=\"200\" />;\n",
    "react-js-styled-components": "import React from \"react\";\nimport CharacterCountWithCustomRows from \"@govtnz/ds/build/react-js-styled-components/CharacterCountWithCustomRows\";\n\nexport default () => <CharacterCountWithCustomRows maxLength=\"200\" />;\n",
    "react-ts-styled-components": "import * as React from \"react\";\nimport * as CharacterCountWithCustomRows from \"@govtnz/ds/build/react-ts-styled-components/CharacterCountWithCustomRows\";\n\nexport default () => <CharacterCountWithCustomRows maxLength=\"200\" />;\n",
    "vue-js": "<template>\n  <character-count-with-custom-rows maxLength=\"200\" />\n</template>\n<script>\nimport Vue from \"vue\";\nimport CharacterCountWithCustomRows from \"@govtnz/ds/build/vue-js/CharacterCountWithCustomRows.vue\";\n\nexport default {\n  components: {\n    \"character-count-with-custom-rows\": CharacterCountWithCustomRows\n  }\n};\n</script>\n",
    "vue-ts": "<template>\n  <character-count-with-custom-rows maxLength=\"200\" />\n</template>\n<script lang=\"ts\">\nimport Vue from \"vue\";\nimport CharacterCountWithCustomRows from \"@govtnz/ds/build/vue-ts/CharacterCountWithCustomRows.vue\";\n\nexport default {\n  components: {\n    \"character-count-with-custom-rows\": CharacterCountWithCustomRows\n  }\n};\n</script>\n",
    "scss": "",
    "html": "<!--\nRemember to add these styles:\nin CSS: CharacterCountWithCustomRows.css\nOR in Sass (SCSS): CharacterCountWithCustomRows.scss\n-->\n<div class=\"g-characterCountWithCustomRows-character-count\">\n  <div class=\"g-characterCountWithCustomRows-form-group\">\n    <label class=\"g-characterCountWithCustomRows-label\"> Full address </label>\n    <textarea class=\"g-characterCountWithCustomRows-textarea\" maxlength=\"200\">\n    </textarea>\n    <span\n      class=\"g-characterCountWithCustomRows-hint g-characterCountWithCustomRows-character-count__message\"\n      aria-live=\"polite\"\n      aria-atomic\n    >\n      You have characters remaining</span\n    >\n  </div>\n</div>\n",
    "css": "",
    "twig-embed": "{% embed \"CharacterCountWithCustomRows.html.twig\"  with {'maxLength':'200'} only %}{% endembed %}"
  }
]