// @autogenerated

// WARNING THIS FILE IS AUTOGENERATED! DO NOT EDIT!

import React from 'react';

import H1 from '@govtnz/ds/build/react-ts/H1.tsx';
import '../../commons/styles/ds/themed-H1.scss';

import PatternsPage from '../../components/PatternsPage';
import onChangeGenerator from '../../commons/onChangeGenerator';

const PageContent = (props) => <React.Fragment><H1 styleSize="xlarge" id="main-heading">Patterns (coming soon)</H1>
<p>Help users by using our patterns which provide easy action flows for specific tasks, as well as templates for common forms.
Typical examples include collecting users&#39; address and contact details, and
guiding users through a step-by-step application form.</p>
<p>We&#39;ll be inviting you to co-design some patterns with us soon. To keep updated
with what we are doing now, what we are planning to do next, and how you can
get involved, <a href="https://confirmsubscription.com/h/j/712F84D0A3086D2B">subscribe to the AOG Design System newsletter</a>.</p>
</React.Fragment>

const template = (props) => {
    return (
        <PatternsPage
            title="Patterns"
            pageProps={props}
            PageContent={PageContent}
        />
    );
};

export default template;
